#默认配置文件
#作者：Zemise_
#version: 1.0

testPassword: 123456

general:
  # 是否允许bStats统计
  allow-bStats: true

  # 是否必须使用命令才能向QQ群发送聊天消息（Bungee下此设置强制为true）
  require-command-to-chat: true

  # 使用命令时是否同时向服务器内发送聊天消息
  command-also-broadcast-to-chat: true

  # 可用的服务器，玩家只有在下面列出的服务器中，QQ群的聊天才会被发送到玩家
  available-servers:
    - Lobby
    - Pure01
    - Creative

  # 是否将上面的列表用作黑名单，即玩家在上面列出的服务器时，QQ群聊天不会发送到玩家
  available-servers-use-as-blacklist: false

  # QQ群消息广播到游戏内聊天的格式（可以使用样式代码）
  # 变量：
  # %groupname% - 群名称
  # %groupid% - 群号
  # %nick% - 发送者群名片
  # %qq% - 发送者QQ号
  # %message% - 消息内容
  in-game-chat-format: "&6[%groupname%] &a%nick%&r: %message%"

  # 是否允许控制台使用聊天命令
  allow-console-chat: false

  # 如果作为控制台发送到QQ群的聊天消息，控制台要叫什么名字
  console-name: "控制台"

  # 游戏聊天前缀（聊天需要带有指定前缀才能发送到QQ群）
  requite-special-word-prefix:
    #启用这个功能
    enabled: true

    # 聊天前缀（可设置多个，群聊天只有带下面的前缀之一才会发送到服务器）
    prefix:
      - "#"

    # 当群名片不存在时是否尝试获取昵称
    use-nick-if-namecard-null: false

    # 已绑定玩家向服务器发送聊天消息的格式
    # 如果玩家没有绑定，消息格式仍按照上方设置的格式发送
    # 内置变量仍然可以使用
    # 额外变量：%player% - 玩家显示昵称
    bind-chat-format: "&6[QQ]&r %player%: %message%"

  # 服务器消息发送到QQ群的格式
  # 自带变量：
  # %player% - 玩家显示昵称
  # %message% - 消息内容
  group-chat-format: "[MC] %player%: %message%"

  # 是否发送玩家进服退服消息
  send-player-join-quit-message: false

  # 进服消息
  # 自带变量：
  # %player% - 玩家显示昵称
  player-join-message: "%player% 进入服务器"

  # 玩家进服消息发送间隔，单位：秒
  # 在此间隔内多次进入不会多次发送群消息
  player-join-message-interval: 0

  # 退服消息
  # 自带变量：
  # %player% - 玩家显示昵称
  player-quit-message: "%player% 离开服务器"

  # 玩家退服消息发送间隔，单位：秒
  # 在此间隔内多次退出不会多次发送群消息
  player-quit-message-interval: 0

# 黑名单
# 无论上方如何设置，下方的黑名单如有匹配则不会进行任何操作（优先级最高）
blacklist:
  # 屏蔽的QQ，插件不会转发此处列出的QQ发出的消息
  qq:
    - 987654
    - 321987

  # 屏蔽的玩家名，插件不会转发此处列出的玩家的所有消息
  player:
    - Steve
    - Alex

  # 屏蔽词，插件不会转发包含下方列出的屏蔽词的消息
  word:
    - example
    - words

bot-account: 2169910495  # QQ bot account
bot-password: 'Abc408880155@'  # QQ bot password
bot-login-device: 'ANDROID_PHONE'  # ANDROID_PHONE, ANDROID_PAD, ANDROID_WATCH, IPAD, MACOS

super-admin-account: [703231137, 456]  # super administrator accounts

player-group: 836289227  # the number of QQ group where players are in 995467297
inner-player-group: 83  # not very useful, just ignore it
op-group: 955953191  # the group where managers and operators in 195984627
check-in-group: 10101  # the group to check in

use-mysql: false  # use MySQL or SQLite
mysql-host:
mysql-port:
mysql-database:
mysql-username:
mysql-password:

QWeather-APIKey: 'qwq'  # 和风天气API密钥

message-forward:
  group-to-server:
    enable: true
    mode: "all"  # "all" or "prefix"
    #聊天前缀(可设置多个，群聊天只有带有下面的前缀之一才会发送到服务器)
    # ignore this if the mode is "all"
    prefix:
      - "."
      - "-"
  server-to-group:
    enable: true
    mode: "all"
    prefix: "."

bot-speak-possibility: 5  # percent  # bot may seldom speak something written at "messages.yml" - "bot-greetings", set this number to decide the possibility, set to 0 to disable

message-head-format: '&f<&b{SENDER}&f> '

bot-command-prefix: '#'
console-command-prefix: '/'

bind-id-and-qq:
  # this function MUST be enabled
  online-mode: true
  whitelist: true  # recommend enabling this in order for a better experience
  modify-namecard: true

tps-check:
  enable: true
  interval: 1  # minutes
  threshold: 17.0  # ticks  # when server TPS is lower than this number, send a warning message to the op-group above

online-player-record:
  enable: false
  interval: 10  # minutes

message-length-limit:
  enable: true
  ignore-ops: true
  maximum-length: 60  # chars

# Stp is needed
stop-server:
  teleport-players:
    enabled: false
    target-server: 'Lobby'

daily-greetings:
  morning:
    enable: true
    cron: '0 0 7 * * ?'
    city: '苏州'
  night:
    enable: true
    cron: '0 0 23 * * ?'

# bot may repeat the message that has been repeated several times
bot-repeater:
  enabled: true
  # NEVER set this to 1 unless you simply want a repeater
  frequency: 3  # counts  # set this number to decide the frequency

block-words:
  enabled: true
  warning-message: '你的消息含有屏蔽词，已撤回'  # set this an empty string ('') to disable sending warning message
  blocklist:
    - '（脏话）'
    - '（敏感词）'

CC-images:
  get-image:
    enable: false
  upload-image:
    enable: false
    # using Baidu AI API to detect cat, see in https://ai.baidu.com/ai-doc/IMAGERECOGNITION/Zk3bcxdfr
    cat-detect:
      enable: false
      api-key: vn3fu4i67oxxxxxxx
      secret-key: XXXXXXXXXXXXXX
      access-token: 24.xxxxxx  # you MUST NOT modify this
      require-score: 0.1
    limit:
      enable: true
      bypass-op: false
      max-image-size: 2048  # kb
      cooldown: 5  # minutes
      max-images-per-day: 10

# 除非你已接入Cellcraft审核专用系统 COPA，否则请禁用此项
player-group-auto-manage:
  enable: false
  reject-message: '请加群 705754458 以获取入群验证码'

check-in-group-auto-manage:
  enable: true
  minimum-QQ-level: 10  # 最低QQ等级，防小号。设置为 0 则关闭检测

# 测试功能
netease-cloud-music:
  profile:
    phone: '10000000000'
    password: 'qwerty123456'

# 弃用功能
inner-player-group-auto-manage:
  invite:
    enable: true
    cron: '0 0 0/1 * * ?'
    requirement: 1000  # minutes per week
    blacklist:
      - 'qwq'
      - 'qaq'
  kick:
    enable: true
    cron: '0 0 18 ? * 7'
    requirement: 1000
    whitelist:
      - 'zemise'
      - 'abc'
